### ISSUE TITLE
Ionic Keyboard Fails build in cordova-ios 4.0

### ISSUE THREAD

**Issue by jfkoch** [driftyco/ionic-plugin-keyboard#102]
CompileC build/GodsEye.build/Debug-iphonesimulator/GodsEye.build/Objects-normal/i386/IonicKeyboard.o GodsEye/Plugins/com.ionic.keyboard/IonicKeyboard.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/joshk/Snaportation/platforms/ios/cordova/build-debug.xcconfig,-project,GodsEye.xcodeproj,ARCHS=i386,-target,GodsEye,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/joshk/Snaportation/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/joshk/Snaportation/platforms/ios/build/sharedpch
Error: /Users/joshk/Snaportation/platforms/ios/cordova/run: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by jfkoch** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6157464/8100468/18f6da7e-0fc9-11e5-82c6-17383ca8d1bf.jpg)

**Comment by nwidal** [comment]
Got the same problem here. Do you have figured out a workaround to this?

**Comment by tlancina** [comment]
Hmm, I'm not sure why `self.webView` is not a UIWebView.  Possibly related: https://issues.apache.org/jira/browse/CB-8659.  

This is really just a stab in the dark, but if you change https://github.com/driftyco/ionic-plugin-keyboard/blob/master/src/ios/UIWebViewExtension.m#L7 from `@implementation UIWebView (HackishAccessoryHiding)` to `@implementation UIView (HackishAccessoryHiding)` does that make it work? The method we're adding with the category extension just loops through subviews, so as long as it has a scroll view, I think it shouldn't really matter if it's UIWebView or a UIView.

**Comment by apipemc** [comment]
I had the same issue. and updating solutions as all libraries.
npm install -g ionic && cordova && ios-sim && ios-deploy

**Comment by runspired** [comment]
Still seeing this issue, be it noted that this is cordova-ios 4 + wkWebView beta.  So it won't be a UIWebView isntance.

**Comment by mrichie** [comment]
Still error on cordova@4.x

**Comment by tlancina** [comment]
Should be fixed in 1.0.8, if it's not let me know!

**Comment by gsanjeevkumar** [comment]
I see this problem still appearing. Is this fixed ... pls help

**Comment by axtscz** [comment]
I'm still having this issue as well.

**Comment by jsolano** [comment]
same here... :(

**Comment by axtscz** [comment]
Removing and adding the keyboard plugin again solves this.

**Comment by axtscz** [comment]
Removing and adding the keyboard plugin again solves this.

`cordova plugin rm com.ionic.keyboard`

**Comment by Peege151** [comment]
@axtscz running those commands just reinstalls v1.0.4 for me.

**Comment by axtscz** [comment]
Try this:

cordova plugin add com.ionc.keyboard@1.0.8

Alex Cruz

**Comment by Peege151** [comment]
That's a 404. Is ionic-plugin-keyboard not the same as com.ionic.keyboard?

**Comment by jetma** [comment]
@Peege151 for me ionic-plugin-keyboard is the same as com.ionic.keyboard
`cordova plugin add ionic-plugin-keyboard`

**Comment by axtscz** [comment]
Ditto, they are both the same thing.

**Comment by tlancina** [comment]
Hey all, just a quick explanation since there seems to be some confusion on this.

On April 21, 2015 Cordova moved plugins from their registry to npm: https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html.

`com.ionic.keyboard` is from the old registry, which didn't allow uploads after the move, so there is no way to update that name.  It is stuck at version 1.0.4, which causes this issue.

`ionic-plugin-keyboard` is the plugin on npm, and is up to date. It is currently at version 1.0.8.

To install the latest version of the keyboard plugin, use `cordova plugin add ionic-plugin-keyboard`.

If you are currently able to install `com.ionic.keyboard` you probably need to update your version of Cordova, since I believe trying to add plugins from the old registry doesn't work anymore.

Hope this clears things up a little!

**Comment by Dinesh7052** [comment]
cordova plugin rm com.ionic.keyboard
cordova plugin add com.ionic.keyboard

I have fixed this issue.please use this comment and in app.js 
cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);
